baseURL = "https://bombrary.github.io/blog/"
languageCode = "ja-jp"
title = "Chanomic Blog"
theme = "ch-modified"
pygmentsStyle = "github"
pygmentsUseClasses = true
publishDir="docs"

[taxonomies]
tag = "tags"
categories = "categories"
