baseURL = "https://bombrary.github.io/blog/"
title = "Chanomic Blog"
author = "bombrary"
paginate = 3
languageCode = "ja-jp"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "ch-modified"
publishDir="docs"
pygmentsUseClasses = true
googleAnalytics="UA-152083322-1"

[menu]

# 気が向いたら設定する
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

