baseURL = "https://bombrary.github.io/blog/"
title = "Chanomic Blog"
pagination.pagerSize=10
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

author = "bombrary"
DefaultContentLanguage = "en"
languageCode = "ja-jp"
enableInlineShortcodes = true
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true
enableGitInfo = true

[services.googleAnalytics]
ID = "G-3XDB2CF6Q4"

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production" # to enable google analytics, opengraph, twitter-cards and schema.

title = "Chanomic Blog"
description = "Chanomic Blog"
keywords = ["Blog", "Portfolio", "PaperMod"]
DateFormat = "2006-01-02"
defaultTheme = "dark" # dark, light
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false

hideauthor = true
hidemeta = false
hideSummary = false

showtoc = true
tocopen = false


[params.assets]
disableHLJS = true # to disable highlight.js

[params.analytics.google]
SiteVerificationTag = "BkKXZW5Wg63My_E2g1_KhUdnMEVtwDSC_epgk7d584E"

[params.cover]
hidden = true # hide everywhere but not in structured data
hiddenInList = true # hide on list pages and home
hiddenInSingle = true # hide on single page

# for search
# https://fusejs.io/api/options.html
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
keys = ["title", "permalink", "summary", "content"]


[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/archives/"
weight = 30

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40

[markup.highlight]
noClasses = true
anchorLineNos = false
codeFences = true
guessSyntax = true
lineNos = true
